# datos_prueba.py
DATOS_PRUEBA = {
    "¿Qué candidato presidencial habla mucho más sobre reducir la delincuencia?": {
        "respuesta_generada": "Metadatos: candidato: Wilson Gomez, descripción: Entrevista en la que un candidato presidencial de Ecuador presenta su visión y propuestas para el pas, abordando temas clave como la conformación de su binomio, su experiencia en el sector pblico y su plan de goberno. Se enfatiza un enfoque de transformación dividido en dos fases: una inicial para rescatar al pas y otra para transformarlo, priorizando seguridad, empleo, salud y educación. También se discute la estrategia en seguridad con el uso de tecnologa y el fortalecimiento de instituciones judiciales y policiales. La crisis energética es",
        "respuesta_esperada": "El candidato que ha puesto mayor énfasis en la reducción de la delincuencia es Wilson Gómez. Durante su campaña, ha destacado un enfoque de transformación dividido en dos fases: una primera etapa para rescatar al país y una segunda para su transformación. Su estrategia en seguridad incluye el uso de tecnología avanzada y el fortalecimiento de las instituciones judiciales y policiales, con el objetivo de combatir la criminalidad de manera estructural. Además, ha señalado la importancia de la transparencia en la gestión pública y la eficiencia en la administración gubernamental como pilares fundamentales para recuperar la confianza ciudadana."
    },
    "¿Dame informaciòn acerca de Noboa?": {
        "respuesta_generada": "Metadatos: candidato: Daniel Noboa, descripción: El conversatorio abordó temas clave como democracia y participación ciudadana, destacando la importancia del voto informado y la necesidad de fortalecer la institucionalidad. En seguridad, se discutieron la sobrepoblación carcelaria, el uso de cárceles barcazas, la reforma del SNAI y la implementación del plan Fénix con tecnologa y inteligencia. En economa y empleo, se planteó la creación de empleo de calidad, el impulso a sectores estratégicos como la industria 4.0 y la",
        "respuesta_esperada": "Daniel Noboa ha abordado temas clave como democracia y participación ciudadana, destacando la importancia del voto informado y la necesidad de fortalecer la institucionalidad. En seguridad, ha discutido la sobrepoblación carcelaria, el uso de cárceles barcazas, la reforma del SNAI y la implementación del plan Fénix con tecnología e inteligencia. En economía y empleo, ha planteado la creación de empleo de calidad, el impulso a sectores estratégicos como la industria 4.0 y la infraestructura. También ha tratado la atracción de inversión extranjera, la competitividad, la reducción de costos en electricidad y combustibles, y la diferenciación entre gasto e inversión."
    },
    "¿Qué candidato presidencial habla mucho más de infraestrura?": {
        "respuesta_generada": "Metadatos: candidato: Pedro Granja, descripcion: Entrevista centrrada en los temas de Salud mental y bienestar, Poltica criminal, Economa y desarrollo, Educación y reforma docente, con propuestas concretas enfocadas en resolver desafos nacionales., temas_tratados: Salud mental y bienestar, Poltica criminal, Economa y desarrollo, Educación y reforma docente, con propuestas concretas enfocadas en resolver desafos nacionales., temas_tratados: Salud mental y bienestar, Poltica criminal, Economa y desarrollo, Educación y reforma docente, con propuestas concretas enfocadas en resolver desafos",
        "respuesta_esperada": "El candidato que ha hablado más sobre infraestructura es Francesco Tabacchi. Durante su campaña, ha propuesto mejorar la infraestructura a través de la inversión privada en sectores estratégicos como el petróleo y la minería. También ha planteado el desarrollo de concesiones de obra pública y la transformación del sector agropecuario hacia la agricultura 4.0. Además, ha destacado la importancia de garantizar un entorno seguro para los inversionistas y generar empleo mediante proyectos de infraestructura y desarrollo económico."
    },
    "¿Crísis energética en el Ecuador?": {
        "respuesta_generada": "Metadatos: candidato: Daniel Noboa, descripción: Un Ecuador conectado, preparado para el futuro, con ciudades resilientes y ecosistemas protegidos Conservación ambiental, adaptación y mitigación al cambio climático Promover la conservación y protección del medio ambiente, la conservación de la biodiversidad y el desarrollo sostenible como pilares",
        "respuesta_esperada": "Daniel Noboa ha abordado la crisis energética en Ecuador, destacando estrategias para diversificar la matriz energética con la integración de energías renovables y la recuperación de centrales térmicas. También ha resaltado la importancia de la modernización de la infraestructura eléctrica y la optimización del uso de los recursos naturales no renovables. Su enfoque incluye medidas para mejorar la eficiencia energética y fomentar un desarrollo sostenible, con un énfasis en la conectividad digital y física del país."
    },
    "¿Cuál es el candidato que habla más sobre la corrupción?": {
        "respuesta_generada": "Metadatos: candidato: Francesco Tabaqui, descripcion: Francesco Tabaqui, candidato presidencial por el movimiento Creo, expone sus propuestas para mejorar la seguridad, la economa y el sector agropecuario de Ecuador. Critica las polticas fiscales del gobierno actual, afirmando que no se deben aumentar los impuestos. Propone abrir la puerta a la inversion privada en sectores estratégicos como el petróleo y la minera, as como transformar la agricultura hacia la “agricultura 4.0”. En materia de seguridad, Tabaqui aboga por un enfoque de mano dura y mano justa, tomando ejemplos de El Salvador para combatir la delincuencia. T",
        "respuesta_esperada": "Francesco Tabaqui, candidato presidencial por el movimiento Creo, expone sus propuestas para mejorar la seguridad, la economía y el sector agropecuario de Ecuador. Critica las políticas fiscales del gobierno actual, asegurando que no se deben incrementar los impuestos. Propone permitir la inversión privada en sectores estratégicos como el petróleo y la minería, además de transformar la agricultura hacia un modelo de agricultura 4.0. En seguridad, Tabaqui defiende un enfoque de mano dura y mano justa, tomando referencias de El Salvador para enfrentar la delincuencia. También destaca la importancia de fomentar el empleo, fortalecer la infraestructura y garantizar un entorno estable para los inversionistas."
    },
    
}
